version: '3'

services:
  # The load balancer
  nginx:
    image: nginx:1.25.4-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

  # The web server1
  web:
    image: nginx:1.25.4-alpine
    volumes:
      - ./monitoring_start_page/index.html:/usr/share/nginx/html/index.html