global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'server_metrics'
    static_configs:
      - targets: ['158.160.113.40:9100']
    metrics_path: /metrics
    scheme: http
