version: '3'
services:
  registry:
    image: registry:2
    restart: always
    container_name: registry
    ports:
    - "5000:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry-Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.passwd
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - registrydata:/data
      - ./auth:/auth
    networks:
      - nginx-proxy-manager

  registry-ui:
    image: joxit/docker-registry-ui:static
    restart: always
    container_name: registry-ui
    ports:
      - "8081:80"
    environment:
      - REGISTRY_TITLE=MyRegistry
      - REGISTRY_URL=http://registry:5000
      - REGISTRY_UI_AUTH_ENABLED=true
      - REGISTRY_UI_AUTH_REALM="Registry UI"
      - REGISTRY_UI_AUTH_PATH=/auth-ui/htpasswd
    depends_on:
      - registry

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../simplest-PWA-web-application:/usr/share/nginx/html/pwa-web-app
      - ../static:/usr/share/nginx/html/static
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/private:ro
      - ./ssl/ssl_password.pass:/etc/keys/global.pass:ro
      - nginx-logs:/var/log/nginx
    networks:
      - nginx-proxy-manager
networks:
  nginx-proxy-manager:
    driver: bridge

volumes:
  nginx-logs:
    name: nginx-logs
    external: true
  registrydata:
    driver: local