version: '3'
services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../simplest-PWA-web-application:/usr/share/nginx/html/pwa-web-app
      - ../static:/usr/share/nginx/html/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/private:ro
      - ./ssl/ssl_password.pass:/etc/keys/global.pass:ro
      - nginx-logs:/var/log/nginx
    networks:
      - nginx-proxy-manager
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: nginx.access
networks:
  nginx-proxy-manager:
    driver: bridge

volumes:
  nginx-logs:
    name: nginx-logs
    external: true