version: "3.3"
services:
  portainer:
    image: portainer/portainer-ce:latest
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/portainer_data:/data
    ports:
      - "80:9000"
      - "9443:9443"
    restart: always